# Generated by Django 4.2.1 on 2025-04-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_coment_coment_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='coment_pic',
            field=models.ImageField(blank=True, null=True, upload_to='comment_pics/'),
        ),
    ]
